version: '2'
services:
  nopor:
    build: .
    container_name: "nopor"
    image: golang:latest
    ports:
      - 4040:4040
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet